language: node_js
node_js:
  - 16
branches:
  only:
    - develop
    - main

services:
  - docker

install:
  - docker run --name=point -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=point -p 6603:3306 -d mysql:latest
  - sleep 10
  - npm install
  - npx sequelize-cli db:migrate

jobs:
  fast_finish: true
  include:
    - script: npm run unittest
    - script: npm run intergrationtest
    - script: npm run endpointtest
