language: node_js
node_js:
  - 16
branches:
  only:
    - develop
    - main

services:
  - docker

before_install:
  - docker run --name=point -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=point -p 6603:3306 -d mysql:latest

install:
  - npm install
  - npx sequelize-cli db:migrate

after_success:
  - npm run test